zahl = input("Gib eine Zahl ein: ")
zahl2 = input("Gib eine zweite Zahl ein: ")
print("Ergebnis Addition von ", zahl, "+", zahl2, "=", float(zahl1) + float(zahl2))
print("Ergebnis Subratktion von ", zahl, "-", zahl2, "=", float(zahl1) - float(zahl2))
print("Ergebnis Multiplikation von ", zahl, "*", zahl2, "=", float(zahl1) * float(zahl2))
print("Ergebnis Division von ", zahl, "/", zahl2, "=", float(zahl1) / float(zahl2))